name: Secret Scanning Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scanning:
    permissions: 
      contents: read
      pull-requests: write
      security-events: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run secret scanning action
      env:
        GITHUB_TOKEN: ${{ github.token }}
        CONFIG_REPO: ${{ github.repository }}
        CONFIG_PATH:  policy.yaml
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: python main.py
