name: Secret Scanning Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run secret scanning action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_REPO: ${{ secrets.CONFIG_REPO }}
        CONFIG_PATH: ${{ secrets.CONFIG_PATH }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: python main.py
